name: Release Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload assets to GitHub, Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: KSyWOxT5
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 431430
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: ""
          loaders: |
            neoforge
      - name: Upload checksum
        id: upload-release-assets
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["build/checksums/*.sha512"]'
